spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.245.131
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#zuul 已经集成了 ribbon，默认已经实现了负载均衡
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
#需要开启ribbon重试，默认不开启
zuul:
  retryable: true
#  zuul 会过滤敏感 http 协议头，默认过滤以下协议头：
#Cookie
#Set-Cookie
#Authorization
  sensitive-headers:
  
#重试ribbon参数
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
#zuul + hystrix 熔断
#降低 hystrix 超时时间，以便测试降级
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

# 暴露 hystrix.stream 监控端点
# zuul 已经包含 actuator 依赖
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
       

